### PR TITLE
nsize function for CFVariable

### LINKED ISSUE #52: Make `size` of a NCDataset/CFVariable return a NamedTuple instead
I think it would be super-useful to have `size` of some `CFVariable` return a named tuple instead of just a tuple, like so:

Current
```
julia> fld
toa_sw_all_mon (360 × 180 × 228)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Top of The Atmosphere Shortwave Flux, All-Sky conditions, Monthly Means
   standard_name        = TOA Shortwave Flux - All-Sky
   CF_name              = toa_outgoing_shortwave_flux
   comment              = none
   units                = W m-2
   valid_min            =       0.00000
   valid_max            =       600.000
   _FillValue           = -999.0

julia> size(fld)
(360, 180, 228)
```

proposed:
```
julia> size(fld)
(lon = 360, lat = 180, time = 228)
```
this is non-breaking, as the result can still be accessed with integer indices. But it can be also accessed with name, which is super intuitive and gets rid of the problems "which dimension is which".

### PR DESCRIPTION
**Pull request by Datseris**
Closes #52

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Thanks for your PR. Do you know of any other package/array type implementing such a function? We might consider to use the same name for the function. In any case, I actually do prefer to not reuse `size`.

**Comment by Datseris** [comment]
I don't know of any, but naming is very easy to change and deprecate in favor of a better name. If you have a better suggestion go ahead (I actually like `nsize`).

**Comment by Datseris** [comment]
If you don't like `nsize` we could do `namedsize` or `dimensionsize` or `dimensions` (which would also be defined for an `NCDataset` directly).

**Comment by Balinus** [comment]
How about `dimsize()`?

**Comment by Alexander-Barth** [comment]
I like `dimsize` too! Thanks to both for you!

**Pull request merged**
