### PR TITLE
use Ref instead of size 1 Vector

### PR DESCRIPTION
**Pull request by visr**
Ran into this at #88 and update 1 in e02929697b71dc9add90bf57673932829f987504. This updates all the others. Interestingly it looks like this change actually exposed a few existing issues.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Thanks for this PR. If I see correctly, your  PR works on Julia 1.5 and nightly but fails on 1.0. However, using NetCDF_jll will require julia 1.3 anyway.

**Comment by visr** [comment]
Yes indeed, I just did a quick rebase on top of the new master, expecting tests to pass now.

**Comment by visr** [comment]
Do you want to retain Appveyor and Travis build besides the Github Actions by the way? I notice they are much slower.

**Comment by Alexander-Barth** [comment]
Indeed, I will remove Travis. But I plan to keep Appveyor as I don't know who will be the next who will charge for CI :-)
Thanks for the re-base!

**Pull request merged**
