### PR TITLE
Improve README, add TOC, add alias NCDataset

### PR DESCRIPTION
**Pull request by Datseris**
With this PR I am hoping to improve the README a bit by adding a table of contents, re-arranging things for the docs to be a bit more intuitive and adding slightly more info here and there.

I am also adding the `NCDataset` alias (if you approve) for two reasons:
1. In DynamicalSystems.jl we also use the same name, `Dataset` for a central structure.
2. Because it is typical that a julia package "ThisThings.jl" would define a central structure `ThisThing` (without final s).

### CODE REVIEW

**Comment by Datseris** [comment]
See https://julialang.github.io/Pkg.jl/v1/creating-packages/index.html , regarding pluralized names.

**Comment by Datseris** [comment]
(actually according to this style guideline there should only be `NCDataset` , but of course you may not want to go forward with such a hugely breaking change)

**Comment by Datseris** [comment]
Well, coveralls will complain no matter what I'll do, so I'll leave it as is.

**Comment by Alexander-Barth** [comment]
Don't worry about coverage, it's just 0.1 %
I am currently away from my laptop. What do you think, how likely is PR to break user code? 
Thanks!

**Comment by Datseris** [comment]
> What do you think, how likely is PR to break user code? 

Exactly zero! :D  There is no change in code, I've only added the alias `NCDataset` (which means that besides `Dataset` you can use `NCDataset`). Everything else is documentation improvements.

**Comment by Alexander-Barth** [comment]
Ok, thank you for your contribution!

**Comment by Datseris** [comment]
> Ok, thank you for your contribution!

Oh you are welcome, and there are many more to come (see here https://discourse.julialang.org/t/newcomer-contributor-in-juliageo-and-co-help-me-get-started/32480/7 )

**Pull request merged**
