### PR TITLE
add merge function

### LINKED ISSUE #77: [DOC] How to merge 2 NCDatasets (same dims/attributes)
I have two `.nc` files which I load into 2 `NCDataset`s. Both files come from the same dataset (CERES EBAF), and have identical global attributes as well as dimensions.

I am looking for a simple way to merge these two into one `NCDataset`, but I can't figure out a simple way to do this. I imagine it is possible by re-creating every single variable via `defVar`, but there are a lot of them... is there any simpler way?

### PR DESCRIPTION
**Pull request by Datseris**
Closes #77

I need some support on how to test this properly, because in #77 I report that this hits a bug from NCDatasets.jl when applied to real data.

### CODE REVIEW

**Comment by Alexander-Barth** [comment]
Can you create a test function like `test_merge.jl` that merges two NetCDF files (you might want to use ncgen to generate the sample files) ? Maybe it is possible to reuse a significant part of `MFDataset` by making it a bit more flexible (for a in-memory representation of the merged dataset).

**Comment by Datseris** [comment]
I've added a rudimentary test for `merge!`. Unfortunately I cannot replicate the bug I reported in #77 for this trivial field that I use in this example. Can we somehow modify the error message that I get:
```
ERROR: NCDatasets.NetCDFError(-62, "NetCDF: One or more variable sizes violate format constraints")
Stacktrace:
 [1] check at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\errorhandling.jl:29 [inlined]
 [2] nc_enddef at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\netcdf_c.jl:986 [inlined]
 [3] datamode at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\dataset.jl:139 [inlined]
 [4] setindex!(::NCDatasets.Variable{Float32,3}, ::Array{Float32,3}, ::Colon) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\indexing_in_vars.jl:61
 [5] setindex!(::NCDatasets.CFVariable{Union{Missing, Float32},3,NCDatasets.Variable{Float32,3},NCDatasets.Attributes,NamedTuple{(:fillvalue, :scale_factor, :add_offset, :calendar, :time_origin, :time_factor),Tuple{Float32,Nothing,Nothing,Nothing,Nothing,Nothing}}}, ::Array{Union{Missing, Float32},3}, ::Colon) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\indexing_in_vars.jl:299
 [6] #_defVar#21(::Dict{String,Any}, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(NCDatasets._defVar), ::NCDataset,
::String, ::Array{Union{Missing, Float32},3}, ::Type, ::Tuple{String,String,String}) at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:256
 [7] #_defVar at .\none:0 [inlined]
 [8] #defVar#18 at C:\Users\m300808\.julia\packages\NCDatasets\Zwnti\src\core\variables.jl:196 [inlined]
 [9] (::NCDatasets.var"#kw##defVar")(::NamedTuple{(:attrib,),Tuple{Dict{String,Any}}}, ::typeof(defVar), ::NCDataset, ::String, ::Array{Union{Missing, Float32},3}, ::Tuple{String,String,String}) at .\none:0
```

So that it somehow tells me "which" variable is the one with the problem? Then I will be able to test this in more detail. Because at the moment, I cannot imagine one variable being problematic, they are all defined with respect to the same dimensions.

**Comment by Datseris** [comment]
@Alexander-Barth I think the tests are in need of getting organized a bit. The function `example_file` from the file `test_catarrays.jl` is very useful and should exist in general in the package I feel. Like, in the sense that it is a useful tool that provides with usess with a "safe" nc file that they can use to interactively and exploratorily learn NCDatasets, without worrying about their real world data.

**Comment by Datseris** [comment]
Using these new keywords `include, exclude` I have found some culprits. For example, when I try to merge the following variable:

```
julia> ceres["toa_net_clr_t_mon"]
toa_net_clr_t_mon (360 × 180 × 231)
  Datatype:    Float32
  Dimensions:  lon × lat × time
  Attributes:
   long_name            = Top of The Atmosphere Net Flux, Clear-Sky (for total region) conditions, Monthly Means
   standard_name        = TOA Net Flux - Clear-Sky (for total region)
   CF_name              = none
   comment              = Clear-sky flux computed by radiative transfer model where clouds are removed from the atmospheric column, which is more consistent with the way in which climate models define clear-sky flux.
   units                = W m-2
   valid_min            =      -400.000
   valid_max            =       400.000
   _FillValue           = -999.0
```

into the following file
```
julia> NCDataset(CERES3)
NCDataset: C:\Users\m300808\ownCloud\Projects\AlbedoProperties\data\CERES\CERES_EBAF_SFC.nc
Group: /

Dimensions
   lon = 360
   lat = 180
   time = 231

Variables
  lon   (360)
    Datatype:    Float32
    Dimensions:  lon
    Attributes:
     long_name            = longitude
     standard_name        = longitude
     units                = degrees_east
     valid_range          = Float32[-180.0, 360.0]

  lat   (180)
    Datatype:    Float32
    Dimensions:  lat
    Attributes:
     long_name            = latitude
     standard_name        = latitude
     units                = degrees_north
     valid_range          = Float32[-90.0, 90.0]

  time   (231)
    Datatype:    Int32
    Dimensions:  time
    Attributes:
     long_name            = time
     units                = days since 2000-03-01 00:00:00
     delta_t              = 0000-00-01 00:00:00

  sfc_sw_down_all_mon   (360 × 180 × 231)
    Datatype:    Float32
    Dimensions:  lon × lat × time
    Attributes:
     long_name            = Surface Shortwave Flux Down, All-Sky conditions, Monthly Means
     standard_name        = Surface Shortwave Flux Down - All-Sky
     CF_name              = surface_downwelling_shortwave_flux_in_air
     comment              = none
     units                = W m-2
     valid_min            =       0.00000
     valid_max            =       520.000
     _FillValue           = -999.0

  sfc_sw_down_clr_c_mon   (360 × 180 × 231)
    Datatype:    Float32
    Dimensions:  lon × lat × time
    Attributes:
     long_name            = Surface Shortwave Flux Down, Clear-Sky (for cloud-free areas of region) conditions, Monthly
Means
     standard_name        = Surface Shortwave Flux Down - Clear-Sky (for cloud-free areas of region)
     CF_name              = surface_downwelling_shortwave_flux_in_air_assuming_clear_sky
     comment              = none
     units                = W m-2
     valid_min            =       0.00000
     valid_max            =       520.000
     _FillValue           = -999.0

  sfc_sw_down_clr_t_mon   (360 × 180 × 231)
    Datatype:    Float32
    Dimensions:  lon × lat × time
    Attributes:
     long_name            = Surface Shortwave Flux Down, Clear-Sky (for total region) conditions, Monthly Means
     standard_name        = Surface Shortwave Flux Down - Clear-Sky (for total region)
     CF_name              = none
     comment              = Clear-sky flux computed by radiative transfer model where clouds are removed from the atmospheric column, which is more consistent with the way in which climate models define clear-sky flux.
     units                = W m-2
     valid_min            =       0.00000
     valid_max            =       520.000
     _FillValue           = -999.0

```

(the file continues for a long time)

I get the standard error that I have pasted before: `ERROR: NCDatasets.NetCDFError(-62, "NetCDF: One or more variable sizes violate format constraints")` 


There is nothing wrong with the numeric data I am trying to merge:
```
julia> ceres["toa_net_clr_t_mon"] |> Array
360×180×231 Array{Union{Missing, Float32},3}:
[:, :, 1] =
 -149.535  -147.087  -134.816  -129.355  -123.022  …  -184.201  -184.358  -179.904  -182.688  -182.065
 -149.535  -147.087  -134.816  -129.355  -123.024     -184.194  -184.358  -179.904  -182.819  -182.062
 -149.535  -147.087  -134.816  -129.356  -123.022     -184.175  -184.608  -179.904  -183.008  -184.691
 -149.535  -147.088  -134.816  -129.356  -123.022     -184.173 
```

where is this error coming from?

**Comment by Alexander-Barth** [comment]
What happen if a dimensions exists in both datasets but has different length ? A merge function should probably return an error in this case. 

It might even be the cause of the error that you are seeing.

**Comment by Datseris** [comment]
But I've pasted the field I am trying to merge and the fields of the dataset I am trying to merge into. They both clearly show `(360 × 180 × 231)`, so I highly doubt what you are saying is true for my case. 

But of course, in general such a check should happen inside `merge`. My main concern is first understanding where this bug comes from, and then we can add the tests that also cover this bug.

**Comment by Datseris** [comment]
I am happy to share the data I have if it helps, but they can't be uploaded on github (they are circa 2gb)

**Comment by Alexander-Barth** [comment]
For what is is worth, I added an additional check in `defVar` to make sure that an dimension is consistently used with the same length. Unfortunately, I do not have much time to dedicate to this.

In any case, I think it would be preferable to have the merge functionality only virtually (in-memory, not on disk) especially if you work with large files as you do. (https://github.com/Alexander-Barth/NCDatasets.jl/issues/77#issuecomment-584877051).

But if you hit a bug in NCDatasets it would be good to find it.

The dimensions in the  `C:\Users\m300808\ownCloud\Projects\AlbedoProperties\data\CERES\CERES_EBAF_SFC.nc` are:

```
Dimensions
   lon = 360
   lat = 180
   time = 231
```

Can you post also the dimensions in the second file?

**Comment by Datseris** [comment]
Its the same:
```
Dimensions
   lon = 360
   lat = 180
   time = 231
```

all files and variables have the same dimensions.

**Comment by Datseris** [comment]
I'll have a look at the multi-file branch you posted and will report whether this bug persists there or not.

**Comment by Datseris** [comment]
Thanks for merging this! If you could also tag a version I'd appreciate it!

**Pull request merged**
